language: generic
dist: xenial

env:
  global:
    - INSTALL_EDM_VERSION=1.10.0
      PYTHONUNBUFFERED="1"

os:
  - linux
  - osx

cache:
  directories:
    - "~/.cache"

before_install:
  - mkdir -p "${HOME}/.cache/download"
  - if [[ ${TRAVIS_OS_NAME} == 'linux' ]]; then ci/install-edm-linux.sh; export PATH="${HOME}/edm/bin:${PATH}"; fi
  - if [[ ${TRAVIS_OS_NAME} == 'osx' ]]; then ci/install-edm-osx.sh; export PATH="${PATH}:/usr/local/bin"; fi
  - edm install -y click
install:
  - edm run -- python ci/__main__.py build-devenv
script:
  - edm run -- python ci/__main__.py run-tests
