name: Build wheels

on:
  release

jobs:
  buildwheels:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: install cibuildwheel
        run: python -m pip install cibuildwheel==2.2.0a1
    - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
          env:
            CIBW_BUILD_VERBOSITY=1
            CIBW_BEFORE_BUILD="./ci/build-parasail.sh"
    - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl